### ISSUE TITLE
quanX: wps (iOS)误杀反馈

### ISSUE THREAD

**Issue by Chandler-Lu** [GeQ1an/Rules#11]
wps (iOS/iPadOS): 10.7.1

误杀 `mo.res.wpscdn.cn` 导致部分**非广告** banner 和 icon 加载异常
https://github.com/GeQ1an/Rules/blob/41d2d5deebfb4a0ce40ba507405c8e8054ba7b07/QuantumultX/Filter/AdBlock.list#L5463
![IMG_3491](https://user-images.githubusercontent.com/18322610/77865192-ad1c6400-725f-11ea-85fe-8b4f0eb4d992.png)
![IMG_3492](https://user-images.githubusercontent.com/18322610/77865144-69295f00-725f-11ea-86f9-06d71e2bc6ca.png)

**Comment by Chandler-Lu** [comment]
补充一个，`pcbrowser.dd.qq.com`和腾讯翻译君（iOS）的离线翻译包有关，下载地址为`http://pcbrowser.dd.qq.com/pcbrowserbig/translator/nmt/ios_zh_en_v2.zip`

**Comment by GeQ1an** [comment]
已修复。
