### ISSUE TITLE
Quantumult X 规则 Telegram.list 和 Outside.list 中有误。

### ISSUE THREAD

**Issue by nlnlnull** [GeQ1an/Rules#13]
关于 Telegram 的 Quan X 规则使用的 DOMAIN-SUFFIX，应该是 HOST-SUFFIX.

**Comment by GeQ1an** [comment]
已修复。

虽然 Quantumult X 会将 DOMAIN-SUFFIX 处理成 HOST-SUFFIX，使用 DOMAIN-SUFFIX 不影响使用，但这种不够严谨的问题必须修复。
