### ISSUE TITLE
QuantumultX的Outside.list导入时报错

### ISSUE THREAD

**Issue by Jefffish09** [GeQ1an/Rules#16]
用QuantumultX导入https://raw.githubusercontent.com/GeQ1an/Rules/master/QuantumultX/Filter/Outside.list 时，显示“Invalid Line IP6-CIDR,2001:b28:...”

**Comment by Chandler-Lu** [comment]
https://github.com/GeQ1an/Rules/blob/master/QuantumultX/Filter/Outside_old.list

**Comment by Jefffish09** [comment]
> https://github.com/GeQ1an/Rules/blob/master/QuantumultX/Filter/Outside_old.list

Thanks！

**Comment by Chandler-Lu** [comment]
qx v1.0.8已经发布并支持ipv6 CIDR了，可以换回去了

**Comment by Jefffish09** [comment]
> qx v1.0.8已经发布并支持ipv6 CIDR了，可以换回去了

@Chandler-Lu 感谢！已换回去！
