### ISSUE TITLE
quanx代理以下域名可以使得Google Voice正常呼入呼出电话

### ISSUE THREAD

**Issue by Nyim1s** [GeQ1an/Rules#18]
host, voice.telephony.goog, proxy

在接打电话的时候，给对方去电或对方来电，均会无接通音直接进入语音留言（无论自己呼出还是对方呼入）。
通过观察“网络活动”，看到均会有该地址的连接请求，手动添加后，Google Voice可以正常呼入呼出。

（另外：quan添加该规则不好使，依然进语音留言，但是改为添加对应的IP，就好使）

**Comment by GeQ1an** [comment]
将于近期更新。

**Comment by Nyim1s** [comment]
谢谢
