### ISSUE TITLE
油管去广告还是要单独插件吗？

### ISSUE THREAD

**Issue by weigeloveu** [GeQ1an/Rules#25]
打开了油管规则 还是去不掉广告

**Comment by GeQ1an** [comment]
因不能完全去除 YouTube 的广告，且可能会导致一些小问题，所以未添加有关屏蔽 YouTube 广告的规则，若有需求，可在重写中订阅神机规则 [YouTubeAds](https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Rewrite/Block/YouTubeAds.conf) 并启用。
