### ISSUE TITLE
clash的fake-ip-filter子域名匹配

### ISSUE THREAD

**Issue by randyho** [GeQ1an/Rules#28]
子域名匹配要写+，比如*.cmbchina.com会导致招行的app不能正常工作，+.cmbchina.com就可以正常工作

**Comment by GeQ1an** [comment]
是这样吗？我是按照官方支持文档写的，格式没问题呀。
参考 [clash/wiki](https://github.com/Dreamacro/clash/wiki/configuration#fake-ip)

**Comment by randyho** [comment]
*只能匹配一级子域名，+才能匹配多级子域名，你可以验证一下

**Comment by GeQ1an** [comment]
已修改 fake-ip-filter 的所有子域名前缀 * 为 +
