### ISSUE TITLE
Clash配置Proxy Group->Auto->interval数据类型错误

### ISSUE THREAD

**Issue by maddie** [GeQ1an/Rules#3]
在[Clash.yaml的第112行](https://github.com/GeQ1an/Rules/blob/b89e65bf589e25d87cbe89df9f92254c67cb2f22/Clash.yaml#L112)中，Proxy Group `Auto`的`interval`为字符串 `"300"`。正确的类型应该是`integer`，即 `300`。

**Comment by GeQ1an** [comment]
年久失修，有时间了会完善一下。
P.S. 现在 Clash 的各种 API 太多，似乎没有什么必要一直维护下去 😂😂😂

**Comment by maddie** [comment]
我也发现是很久没更新了

主要是我自己写了个程序来生成配置 (proxy + rules)，解析这个规则的时候报错了

**Comment by GeQ1an** [comment]
已更新

**Comment by maddie** [comment]
Thanks!!
