### ISSUE TITLE
Mainland规则更新暴雪相关规则

### ISSUE THREAD

**Issue by zelbloo** [GeQ1an/Rules#34]
可否将战网移除，现在国服已经关了

# > Blizzard
USER-AGENT,hearthstone*,Mainland
HOST,cdp.cloud.unity3d.com,Mainland
HOST-SUFFIX,battle.net,Mainland
HOST-SUFFIX,battlenet.com,Mainland
HOST-SUFFIX,blizzard.com,Mainland

**Comment by GeQ1an** [comment]
ok
