### ISSUE TITLE
规则误杀摸鱼kik

### ISSUE THREAD

**Issue by junetwentytwo** [GeQ1an/Rules#35]
这是一款搜狐出品的App，有些规则会导致视频无法播放，可以排查一下。例如以下这条：

https://h5-ol.sns.sohu.com/hy-moyukik-h5/share/feed/1645401995743359009?sf_my=copylink&cid=026796255891793921280&uid=1066326

**Comment by junetwentytwo** [comment]
是data.vod.itc.cn这条规则reject导致无法播放

**Comment by GeQ1an** [comment]
ok.
